services:
  web:
    build:
      context: .
      dockerfile: 'docker/Dockerfile'
    entrypoint: ["sh", "/app/docker/entrypoint.sh"]
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mysql
    env_file:
      - 'docker/.env.docker'

  celery_worker:
    build:
      context: .
      dockerfile: 'docker/Dockerfile'
    command: celery -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - mysql
      - web
    env_file:
      - 'docker/.env.docker'

  celery_beat:
    build:
      context: .
      dockerfile: 'docker/Dockerfile'
    command: celery -A core beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - mysql
      - web
    env_file:
      - 'docker/.env.docker'

  redis:
    image: redis:7

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
        - 'docker/.env.docker'

volumes:
  mysql_data:
